### read
get http://localhost:3000/players

### read by id
get http://localhost:3000/players/123123qwsdas

### delete
delete http://localhost:3000/players/54mf244klbkja2bg

### post
post http://localhost:3000/players
Content-Type: application/json

{
        "name": "Ronaldo",
        "qualification": 4, 
        "position": "csatar", 
        "club": "Fradi", 
        "age": 22, s
        "nationality": "Brazil"
}

### put
put http://localhost:3000/players/123123qwsdas
Content-Type: application/json

{
        "name": "Ronaldo",
        "qualification": 4, 
        "position": "csatar", 
        "club": "Fradi", 
        "age": 22, 
        "nationality": "Brazil"
}
